### ISSUE TITLE
Unswitchable camera position with camera button

### ISSUE THREAD

**Issue by Epherfoam** [roastedduk/kyuu#22]
**Describe the bug**
A certain device with multiples camera can't seem to use the switch camera button, it throws a Bottom Slider error 

**To Reproduce**
1. Go to `https://kyuu.ducc.pw/join/scan`
2. Click on camera button
3. See error

**Expected behavior**
It should change the camera position after clicked the camera button.

**Screenshot**
![SmartSelect_20220818-132934_Chrome](https://user-images.githubusercontent.com/34813193/185309833-2a87eeab-0540-4fd6-97c7-0153fb785ea1.jpg)

**Smartphone :**
 - Device: Samsung Galaxy S22 Ultra
 - OS: Android 12 
 - Chrome (104.0.5112.69)

**Comment by roastedduk** [comment]
I can't seem to reproduce the issue with both Safari on my iPhone and Chome on my Galaxy Note9. Can you attach the logs?

**Comment by roastedduk** [comment]
Can you try it again? That should fix the problem

**Comment by Epherfoam** [comment]
Ah, it's resolved to each of my testing devices, thank you for your support!
